configure-local-networking.sh
braio is not expected to exist on first run and this message can lead you to believe that an error has occurred.
=> Prevent Device "braio" does not exist when braio is first created

README.rst
Lack of ACPI in guest XML means that virsh shutdown has no effect. As a
workaround, call shutdown from inside the guest before using virsh
destroy (immediate ungraceful shutdown).
=> Add seed shutdown workaround

etc/kayobe/kolla.yml
The issue with docker client timeouts that required a fork of kolla-ansible is
now resolved upstream
=> Use upstream kolla-ansible

etc/kayobe/kolla.yml
The issue with docker client timeouts that required a fork of kolla-ansible is
now resolved upstream
=> Use upstream kolla-ansible (stable/stein)

etc/kayobe/kolla.yml
The issue with docker client timeouts that required a fork of kolla-ansible is
now resolved upstream
=> Use upstream kolla-ansible (stable/train)

README.rst, init-runonce.sh
This will be particularly useful once backported to stable branches
using Python 2, as latest client versions only support Python 3.
(cherry picked from commit 2325e9c024236937570f1b0727f11613fa7e0b13)
=> Install OpenStack clients using upper constraints

README.rst
The `virsh shutdown` command works fine when Kayobe uses a recent version of the libvirt-vm role.
=> Update seed VM shutdown instructions

README.rst, a-universe-from-nothing.sh, configure-local-networking.sh, etc/kayobe/kolla/config/bifrost/bifrost.yml, etc/kayobe/seed-vm.yml, tenks.yml
Using a separate stable/train-centos8 branch, rather than trying to include both paths in one.
=> CentOS 8: update README and scripts (Train)

README.rst, a-universe-from-nothing.sh, etc/kayobe/kolla/globals.yml
Use built-in support in Kolla Ansible for preventing Docker from manipulating iptables, to avoid connectivity issues with instances.
=> Prevent Docker from manipulating iptables

README.rst, a-universe-from-nothing.sh
If SELinux is not disabled permanently, the seed VM won't start after reboot or boot from snapshot.
Closes #51.
=> Disable SELinux permanently

pull-retag-push-images.sh
When called without arguments, this script runs Kayobe like this:
kayobe playbook run ${KAYOBE_CONFIG_PATH}/ansible/pull-retag-push.yml ''
The extra '' argument causes the following error:
Kayobe playbook  is invalid: Path does not exist
This commit only includes this argument if it is non-empty.
Closes #60.
=> Fix pull-retag-push-images.sh when called without arguments

configure-local-networking.sh
systemd-networkd works with these commands, while ifupdown did not.
=> Ubuntu: revert to iproute commands in configure-local-networking.sh

etc/kayobe/ansible/pull-retag-push.yml
By default, Ansible injects a variable for every fact, prefixed with
ansible_. This can result in a large number of variables for each host,
which at scale can incur a performance penalty. Ansible provides a
configuration option [0] that can be set to False to prevent this
injection of facts. In this case, facts should be referenced via
ansible_facts.<fact>.
This change updates all references to Ansible facts from using
individual fact variables to using the items in the
ansible_facts dictionary. This allows users to disable fact variable
injection in their Ansible configuration, which may provide some
performance improvement.
[0] https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inject-facts-as-vars
=> Use ansible_facts to reference facts

etc/kayobe/networks.yml
This was necessary when using MichaelRigart.interfaces on Ubuntu, but
now we use stackhpc.systemd_networkd.
=> Remove pause after interface bounce

etc/kayobe/kolla/globals.yml
True is the default from Wallaby
=> Drop override of docker_disable_default_iptables_rules

pull-retag-push-images.sh
We need to shift command-line arguments, otherwise they are passed to
dev/environment-setup.sh and then to kayobe-env, with the following
failure:
Using Kayobe config from /home/centos/kayobe/config/src/kayobe-config
usage: /home/centos/kayobe/config/src/kayobe-config/kayobe-env [--environment <env-name>]
(cherry picked from commit a4e9603bd02e7bf8cfd770d8251072b885f746ef)
=> Fix calling the pull-retag-push-images script

etc/kayobe/ansible/pull-retag-push.yml
As Zed removes support for binary images, install_type is dropped from
image names [1].
Update playbook to pull the right images.
[1] https://review.opendev.org/c/openstack/kolla-ansible/+/837293
=> Remove kolla_install_type from pull-retag-push playbook

README.rst
- corrected path to vbmc executable
- added a bit of clarification to VNC console check step
=> Xena documentation update

etc/kayobe/ansible/pull-retag-push.yml
- changed pull location to new one in quay.io
- changed tag naming to correct one
=> [DEV-1039] Pull retag push fix

etc/kayobe/seed-hypervisor.yml
Switching the seed hypervisor bootstrap user to $USER because SMS uses cloud-user rather than centos
=> Fix user error on SMS

README.rst, tenks.yml
Our standard lab resources are bigger than they once were.  When running a lab spread over several weeks, it is a frequent occurrence for the controller node to run out of disk or RAM.  This leads to oom-killer, filesystem overflow and other instability we can do without.  Increase both here.
Extends work done on PR https://github.com/stackhpc/a-universe-from-nothing/pull/130
=> Increase resource capacity for lab controller

etc/kayobe/kolla/config/bifrost/bifrost.yml, init-runonce.sh
The old image appears to have been removed:
https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2 Updated with a new image from 2023:
https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20230501.0.x86_64.qcow2
=> update centos image

tenks.yml
This works around failures to boot baremetal instances with Tenks after their deployment with Ironic is complete. See the upstream Kayobe change for more details [1].
While this may break multicast traffic [2], it allows a Universe from Nothing on Rocky Linux 9 to complete and the CirrOS VM is reachable.
[1] https://review.opendev.org/c/openstack/kayobe/+/897260
[2] https://review.opendev.org/c/openstack/tenks/+/736708
=> Disable libvirt_vm_trust_guest_rx_filters

etc/kayobe/globals.yml
In Yoga, Kayobe sets os_release to 8 when os_distribution is rocky. Since we also support Rocky Linux 9, use the version of the lab VM to set the os_release variable.
=> Detect Rocky Linux version

etc/kayobe/ansible/lab-hosts.yml, etc/kayobe/hooks/overcloud-inventory-discover/post.d/01-lab-hosts.yml
Set a hook to a custom playbook for lab hosts so that any newly-discovered hosts will be automatically added to hostname resolution and ssh accesses to those hosts will default to use the stack user.
=> Add /etc/hosts and ssh_config entries for lab hosts

etc/kayobe/ansible/pull-retag-push.yml
The variables `docker_pull_tag` and `kolla_tag` already include `kolla_base_distro` and `kolla_base_distro_version`, so the playbook was trying to pull images with tags like `2023.2-ubuntu-jammy-ubuntu-jammy`, which obviously failed.
=> Fix image tags use in pull-retag-push playbook

configure-local-networking.sh
Commit dc5d16da847aaadc19ae0ebf3e50a0791536f227 inserted apt code in the wrong place, resulting in the following failure on RL9:
sudo: apt: command not found
=> Fix configure-local-networking script on RL9

etc/kayobe/ansible/pull-retag-push.yml
Container images are only updated weekly on Docker Hub.
(cherry picked from commit b1e8999b63d886b791b31ebcf62fe77f47d281cc)
=> Pull container images from Quay.io

etc/kayobe/ipa.yml
The TinyIPA images are broken in master and 2024.1 due to a parted bug in Tiny Core Linux 15 [1].
[1] https://bugs.launchpad.net/ironic-python-agent-builder/+bug/2068936
=> Use CentOS IPA deployment images

.gitreview, etc/kayobe/apt.yml, etc/kayobe/bifrost.yml, etc/kayobe/compute.yml, etc/kayobe/controllers.yml, etc/kayobe/docker.yml, etc/kayobe/globals.yml, etc/kayobe/grafana.yml, etc/kayobe/infra-vms.yml, etc/kayobe/inspector.yml, etc/kayobe/inventory/groups, etc/kayobe/ipa.yml, etc/kayobe/ironic.yml, etc/kayobe/kolla.yml, etc/kayobe/logging.yml, etc/kayobe/monitoring.yml, etc/kayobe/neutron.yml, etc/kayobe/openstack.yml, etc/kayobe/overcloud-dib.yml, etc/kayobe/proxy.yml, etc/kayobe/seed-hypervisor.yml, etc/kayobe/seed-vm.yml, etc/kayobe/seed.yml, etc/kayobe/ssh.yml, etc/kayobe/storage.yml, etc/kayobe/vgpu.yml, setup.cfg, zuul.d/project.yaml
This catches up with years of commits from kayobe-config-dev.
=> Merge kayobe-config-dev master branch

etc/kayobe/kolla/config/bifrost/bifrost.yml
We were pinning to old cloud images, but we should now be able to switch to the latest ones since we use UEFI by default [1].
A recent Bifrost change [2] introduced various improvements surrounding deployment images that are downloaded rather than built locally. Bifrost is now aware of how to download official images, so we only need to specify the Linux distribution and release.
However, there is a bug affecting centos/rocky which are using a different file format for checksums [3]. Disable checksum verification for these distributions until it is fixed.
[1] https://review.opendev.org/c/openstack/kayobe/+/927015
[2] https://review.opendev.org/c/openstack/bifrost/+/884888
[3] https://bugs.launchpad.net/bifrost/+bug/2081031
=> Update to latest cloud images

etc/kayobe/seed-vm.yml
This should not have been hardcoded to use a Rocky Linux image.
=> Revert seed_vm_root_image to default value

etc/kayobe/kolla/config/bifrost/bifrost.yml
Bifrost does not yet support automatic download for Ubuntu Noble, although this is being addressed [1].
[1] https://review.opendev.org/c/openstack/bifrost/+/934177
=> Add support for downloading Ubuntu Noble images

a-universe-from-nothing.sh
This is needed once Kayobe starts requiring Python 3.10 or above [1].
This requires support for the new --python argument of beokay [2].
[1] https://review.opendev.org/c/openstack/kayobe/+/926639
[2] https://github.com/stackhpc/beokay/pull/14
=> Use Python 3.12 on Rocky Linux 9

README.rst, a-universe-from-nothing.sh
This is to have fewer occurences of ``master`` to replace when we branch.
=> Clone default branch of beokay

etc/kayobe/kolla/config/bifrost/bifrost.yml, etc/kayobe/seed-vm.yml, tenks-compute.yml, tenks-storage.yml, tenks.yml
This is needed in order to resolve openssh/openssl build version clash due to 9.3 repo issues.
=> Add EUFI options + Rocky 9.5
