stackhpc/a-universe-from-nothing

README.rst
Now with centralised logging and all!
=> Some additional notes for the README

README.rst, a-universe-from-nothing.sh, etc/kayobe/bifrost.yml, etc/kayobe/ceph.yml, etc/kayobe/compute.yml, etc/kayobe/controllers.yml, etc/kayobe/docker.yml, etc/kayobe/inspector.yml, etc/kayobe/ipa.yml, etc/kayobe/kolla.yml, etc/kayobe/kolla/globals.yml, etc/kayobe/monitoring.yml, etc/kayobe/networks.yml, etc/kayobe/ntp.yml, etc/kayobe/openstack.yml, etc/kayobe/pip.yml, etc/kayobe/seed-hypervisor.yml, etc/kayobe/seed.yml, etc/kayobe/storage.yml, etc/kayobe/swift.yml, pull-retag-push-images.sh
@markgoddard I took your changes and adapted them to cleanly rebase on top of `stable/stein`.
=> Update master for the Train release before branching to stable/train

a-universe-from-nothing.sh
=> Add a script for running a full deployment

README.rst
I'm following through the process for Andalucia, I think this tag needs to be `train-centos8`
=> Pull-retag-push needs to be for train-centos8 tag

etc/kayobe/kolla/kolla-build.conf
=> Fix network connectivity when building container images

etc/kayobe/kolla/config/bifrost/bifrost.yml
(cherry picked from commit 549c889808a9a3c2ef84e6a8a5eb1b8b76ae4ef4)
=> Update overcloud host image to CentOS 8.3

README.rst, a-universe-from-nothing.sh, configure-local-networking.sh, etc/kayobe/a-universe-from-nothing.yml, etc/kayobe/ansible/pull-retag-push.yml, etc/kayobe/compute.yml, etc/kayobe/controllers.yml, etc/kayobe/inventory/group_vars/compute/network-interfaces, etc/kayobe/inventory/group_vars/controllers/network-interfaces, etc/kayobe/inventory/group_vars/seed/network-interfaces, etc/kayobe/kolla.yml, etc/kayobe/kolla/config/bifrost/bifrost.yml, etc/kayobe/networks.yml, etc/kayobe/seed-vm.yml, etc/kayobe/seed.yml
* Update README and a-universe-from-nothing.sh
* Workaround for seed VM provision failure when sudo fails DNS query
* Detect OS distro of Ansible control host and use it to set config
* Pause after interface configuration
* Fix pull-retag-push.yml playbook
=> Add support for running on Ubuntu

README.rst, a-universe-from-nothing.sh
Using the proper commands is more informative than running the Kayobe
test/development scripts.
=> Use manual Kayobe commands to deploy seed hypervisor & VM

README.rst, init-runonce.sh, tox.ini
Fix wallaby upper constraints URL
=> Fix wallaby upper constraints URL

etc/kayobe/kolla/config/bifrost/bifrost.yml
(cherry picked from commit f4c134f8fc594cc54bfec6b8955c7ad0ff6eafaa)
=> Update overcloud host image to CentOS 8.4

README.rst
=> Update bifrost instructions

etc/kayobe/networks.yml
(cherry picked from commit 30a6a0ae9e7844abdb25d7907d397562162268bc)
=> Adapt aio_mtu to OVN defaults

etc/kayobe/apt.yml, etc/kayobe/bifrost.yml, etc/kayobe/compute.yml, etc/kayobe/dnf.yml, etc/kayobe/globals.yml, etc/kayobe/infra-vms.yml, etc/kayobe/inventory/group_vars/infra-vms/ansible-python-interpreter, etc/kayobe/inventory/group_vars/infra-vms/network-interfaces, etc/kayobe/ipa.yml, etc/kayobe/kolla.yml, etc/kayobe/libvirt.yml, etc/kayobe/networks.yml, etc/kayobe/overcloud-dib.yml, etc/kayobe/proxy.yml, etc/kayobe/seed-hypervisor.yml, etc/kayobe/seed-vm.yml, etc/kayobe/time.yml
(cherry picked from commit da0b2626a74efe079636d9a16655cdd6b2cd4553)
=> Synchronise with upstream kayobe-config

README.rst
- corrected vbmc executable path
- added a bit of clarification to VNC console check step
=> documentation update

README.rst
- added kibana note
- added bifrost note
=> added slight clarifications

configure-local-networking.sh
- added logic for installing iptables on ubuntu
=> [DEV-1039] Ubuntu iptables

etc/kayobe/seed-hypervisor.yml
Same reasoning as here, just for Wallaby:
https://github.com/stackhpc/a-universe-from-nothing/pull/132
=> Update user for use on SMS

etc/kayobe/kolla/config/bifrost/bifrost.yml
This brings compatibility with Rocky Linux 9.
=> Update cloud images for Yoga

etc/kayobe/ansible/pull-retag-push.yml
Container images are only updated weekly on Docker Hub.
=> Pull container images from Quay.io

etc/kayobe/kolla/config/bifrost/bifrost.yml, etc/kayobe/seed-vm.yml
A seed VM booted from Rocky Linux 9.4 was stuck in a Grub boot loop.
=> Use Rocky Linux 9.3 images

etc/kayobe/kolla/config/bifrost/bifrost.yml
Proper fixes were merged in Bifrost [1][2].
[1] https://review.opendev.org/c/openstack/bifrost/+/934177
[2] https://review.opendev.org/c/openstack/bifrost/+/929753
=> Remove Bifrost configuration workarounds

README.rst
The README was missing instructions for using Python 3.12.
=> Synchronise README with a-universe-from-nothing.sh
